#
server:
  port: 10111

spring:
  application:
    name: math

  datasource:
    url: jdbc:h2:file:./data/math-db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
  flyway:
    locations: classpath:db/migration
